INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-10, 'Rule 1', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-9, 'Rule 2', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-8, 'Rule 3', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-7, 'Rule 4', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-6, 'Rule 5', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-5, 'Rule 6', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-4, 'Rule 7', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-3, 'Rule 8', 'True', '28/03/2023', '9:10');
INSERT INTO RULES(ID, NAME, ACTIVE, DATE, TIME) VALUES(-2, 'Rule 9', 'True', '28/03/2023', '9:10');

INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-10, 'presence not detected', 1, 'hour', 'above', -10);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-9, 'presence not detected', 1, 'hour', 'above', -9);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-8, 'presence detected', 1, 'hour','below', -8);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-7, 'presence not detected', 1, 'hour','every', -7);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-6, 'presence detected', 1, 'hour','equal', -6);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-5, 'store data', 1, 'hour','previous', -5);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-4, 'store data', 1, 'minute','every', -4);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-3, 'temperature', 25, '°C','above', -3);
INSERT INTO CONDITIONS(ID, NAME, CONDITION_VALUE , CONDITION_UNIT, CONDITION_TYPE, RULE_ID) VALUES(-2, 'temperature', 10, '°C','below', -2);

INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-10, 'turn heating off', -10);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-9, 'turn heating off', -9);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-8, 'turn heating on', -8);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-7, 'turn heating off', -7);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-6, 'turn heating on', -6);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-5, 'store data in a CSV file', -5);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-4, 'store data in a CSV file', -4);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-3, 'turn heating off', -3);
INSERT INTO ACTIONS(ID, NAME, RULE_ID) VALUES(-2, 'turn heating on', -2);